[손명기] (프로그래머스 - 스택, 큐) 기능개발 풀이
2022-2digit-study/2022-algorithm-study pull request #16
Opened 2022-05-26 11:48 UTC by MKsson

2022-05-26 13:41 UTC, YangTaeyoung requested changes
문제 링크를 파일의 가장 위에 남겨주세요.

2022-05-30 07:14 UTC, MKsson commented
> 문제 링크를 파일의 가장 위에 남겨주세요.

수정 후 push 했습니다 ~

2022-05-30 10:19 UTC, MKsson reviewed
기능개발 문제 주소 첨부 했습니다.

2022-05-31 05:41 UTC, YangTaeyoung approved these changes

2022-05-31 05:41 UTC, YangTaeyoung commented on 기능개발.py
> +    for i, j in zip(progresses, speeds):
`i`, `j`와 같은 명명은 리스트의 인덱스를 표현할 때 주로 사용합니다. 하지만 현재 코드속의 `i`, `j`는 인덱스가 아닌, `progressses`, `speeds` 리스트를 직접 순회하고 있으므로 해당 객체가 `progresses`, `speeds` 리스트의 요소임을 표현하는 것이 좋습니다.
```python
for progress, speed in zip(progresses, speeds):
```

2022-05-31 05:41 UTC, YangTaeyoung commented on 기능개발.py
> +        if val[1] > 0:
나머지가 0보다 크면 +1하는 것이  목적으로 보입니다.
if 문을 활용하여 직접 구현한 것도 좋으나, python에서는 math라이브러리에서 올림함수를 제공합니다. 이를 활용하면 5~10번 줄을 다음과 같이 고칠 수 있습니다.
```python
m_list.append(math.ceil((100-i)/j))
```

2022-05-31 05:41 UTC, YangTaeyoung commented on 기능개발.py
> +    m_list = []
리스트의 명명이 모호합니다.

2022-05-31 05:41 UTC, YangTaeyoung commented on 기능개발.py
> +    return answer
세세한 것 말고는 구현이 잘 되었군요. 스택이나, 큐 알고리즘인데, 여기서는 어떤 것이 큐나 스택으로 사용되었을까요?

2022-05-31 07:33 UTC, MKsson commented on 기능개발.py
> +    for i, j in zip(progresses, speeds):
네 습관적으로 i, j 를 사용하다보니 그렇게 표현했네요 감사합니다.

2022-05-31 07:40 UTC, MKsson commented on 기능개발.py
> +    return answer
흠...... 사실 되는데로 짠거라 큐나 스택을 사용한게 어딘지 모르겠어요

2022-06-02 10:07 UTC, merged